### ISSUE TITLE
Search box shows results from wrong search

### ISSUE THREAD

**Issue by mt-xing** [pkyu/coastle#1]
If you type too fast the search box ends up flickering back and forth and sometimes settling on the search for the wrong query:
![image](https://user-images.githubusercontent.com/6147405/230641255-2cf97d0b-3eff-470f-9ad5-d015ec135c0c.png)

It looks like previous requests to the backend aren't being invalidated when a new search query is sent, so if an earlier query (eg: `int`) ends up coming back later than the later, more complete query (`intimid`), then the results from the earlier one end up replacing the later ones and you end up with incorrect results.

**Comment by pkyu** [comment]
Thanks for the analysis, it's really helpful. I'll look into fixing it!

**Comment by pkyu** [comment]
I implemented debouncing. Think the issue should be fixed given the timer is long enough that the API calls don't overwrite each other.
